.circleci/config.yml

- update golang to 1.13 for ci and remove unneeded env sets
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

Update ci to golang latest version

---

.golangci.yml
CHANGELOG_PENDING.md
backend_test.go
common_test.go
db.go
go_level_db_test.go
prefix_db.go
remotedb/grpcdb/server.go
remotedb/remotedb_test.go

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

Add some linters

---

mem_db_test.go

Thought I've found a bug, but it appeared that I simply forgot to call .Next() when iterating over range of keys 🦆 
Still more tests never killed anyone.

memdb: test Iterator

---

c_level_db.go

Problem: An un-used import causes a compilation error (ie in ABCI apps) when using `-tags cleveldb`
Solution: Remove the un-used import.

Remove unused import

---

CHANGELOG.md
backend_test.go
common_test.go
go.mod
go.sum
mem_batch.go
mem_db.go
mem_db_test.go

Fixes #52 (see also https://github.com/tendermint/tendermint/issues/4520). Uses a B-tree for storage, which should significantly improve range scan performance. No breaking changes.
Haven't had time to benchmark this yet, will do so shortly.

memdb: use btree for storage

---

README.md

Fixes #59. Rendered: https://github.com/tendermint/tm-db/blob/erik/database-descriptions/README.md
We should probably specify concurrency and transaction semantics for `tm-db` and the different backends at some point, but I think we should clean up the code a bit and add tests for this first.

README: add database descriptions

---

CHANGELOG.md
backend_test.go
go_level_db.go

Fixes #57. Branched off of #56, rebase onto `master` once merged.

Make GoLevelDB batch.Close() actually close

---

backend_test.go

This tests that a closed batch can be reused as if it were a new one. It is unclear if this is the semantics we want, the alternative is to panic/error on reuse. The latter option might be better for safety, but many of the current backends allow the former so it is less breaking.
Personally I don't have a strong opinion, we just have to choose one or the other.

test: add test of batch reuse semantics

---

backend_test.go

Fixes deadlocks with backends that have locking iterators (namely BoltDB).

test: properly close iterator in assertKeyValues()

---

backend_test.go

As noted in https://github.com/tendermint/tm-db/pull/68#discussion_r390090596

test: defer iter.Close() in assertKeyValues()

---

CHANGELOG.md
boltdb.go
boltdb_batch.go
boltdb_iterator.go

Iterators did not handle the placeholder `"nil"` key used for empty keys (related to #2)

boltdb: handle empty key placeholders in iterators

---

CHANGELOG.md
cleveldb_iterator.go

New tests showed that empty iterator keys causes panics.

cleveldb: fix handling of empty iterator keys

---

CHANGELOG.md
backend_test.go
boltdb.go
boltdb_batch.go
cleveldb.go
cleveldb_batch.go
goleveldb.go
goleveldb_batch.go
memdb.go
memdb_batch.go
prefixdb_batch.go
remotedb/batch.go
remotedb/remotedb.go
rocksdb.go
rocksdb_batch.go
types.go

See discussion in https://github.com/tendermint/tm-db/pull/66#pullrequestreview-371460117.

Calling non-Close() methods on closed or written batches panic

---

.circleci/config.yml

Test all backends in CircleCI. Currently fails, awaiting fixes in #65, #66, and #69.

circleci: run all tests

---

CHANGELOG.md
memdb.go
memdb_iterator.go

B-tree may panic if it is changed during iteration, so we take out a read-lock for the duration.
No tests, since concurrency semantics are undefined and differ across backends (see #62).

memdb: take out read-lock during iteration

---

.github/stale.yml

Stalebot had been turned on for this repo in the org settings but was missing a config file.
No more!

.github: configure stalebot

---

README.md

Should really link to pkg.go.dev, the team is still working on a badge: https://github.com/golang/go/issues/36982

README: add GoDoc badge

---

backend_test.go
memdb.go
test_helpers.go
types.go
util.go

Emphasize that key/value byte slices (both given and returned) are read-only and must not be modified by callers. This is especially important with MemDB, where doing so will modify the value stored in the database - for performance, we do not implicitly copy slices. This can introduce subtle bugs, see e.g. #86.
Also cleans up the interface documentation a bit.

godoc: emphasize read-only key/value slices, tweak interface docs

---

CHANGELOG.md
backend_test.go
boltdb_batch.go
cleveldb_batch.go
goleveldb_batch.go
memdb_batch.go
prefixdb_batch.go
remotedb/batch.go
remotedb/grpcdb/server.go
remotedb/remotedb_test.go
rocksdb_batch.go
types.go

Modify batch `Set`, `Delete`, and `Close` to return errors. The main error condition currently is using closed batches, but future ones include databases which implement batches as transactions (e.g. BadgerDB) and rejecting empty keys (#2).

batch: return errors for all operations

---

CHANGELOG.md
boltdb_iterator.go
cleveldb_iterator.go
goleveldb_iterator.go
memdb_iterator.go
prefixdb_iterator.go
remotedb/iterator.go
remotedb/remotedb_test.go
rocksdb_iterator.go
types.go

The iterator pattern we're using typically panics on use of invalid iterators (including our backends). I've kept this pattern, but tried to reduce the amount of panics and return via `Error()` instead, and also made `Close()` panic.
Our iterator examples did not include checking `Error()`, so this is likely to break many applications that today rely on iterator panics for error handling (e.g. IAVL, see https://github.com/tendermint/iavl/issues/247).
Branched off of #96.

iterator: improve and document error handling

---

.github/workflows/lint.yml

Required by the GitHub lint action.

lint: bump golangci to 1.29

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
badger_db.go
makefile

BadgerDB is pretty heavy, let's not include it by default. Related to #113.

badgerdb: add build tag

---

CHANGELOG.md
goleveldb.go

goleveldb: bound iterator range for improved performance (#134)

---

docs/how_to_release.md

This change adds a doc on how to release tm-db.

docs: add information on how to release tm-db

---

tools/Dockerfile

A prerequisite for #194, which needs an updated Go toolchain version.

Update Go version in the build container.

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
tools/Dockerfile

**Note to reviewers:** Because the tests use the _existing_ image, and we do not have local credentials to manually push a new one, this PR temporarily disables the test cases to get a new image built. I will revert that change after the image updates.
In #195 I updated the Go version, and also swapped from Debian to Alpine for
the base image. This was OK for the build, but it turns out we also use the
same image to run golangci-lint. That action uses a binary for a different
architecture, which fails on this image.
So:
- Keep the Go version, but revert the base image.
- Split image layers to make rebuilds faster.
- Add version labels as arguments.
- Add some documentation to the workflow configs.

build: fix the image to work with golangci-lint

---

tools/Dockerfile

I tried to fold in the change from #197, but it causes Go build
failures due to an incompatible C API. Roll back the version to
the previous one, we can upgrade separately.

Revert rocksdb version at tip.

---

.github/workflows/ci.yml

The leveldb wrapper library requires cgo to build.
Re-enable the test cases commented out by #201.

Enable cgo for testing.

---

go.mod

Update the go.mod file to version 1.16, to allow the retract syntax.
~Requires #195 (or equivalent) to be merged first.~
In addition to this, I think we should move this release into a separate branch, revert the changes from master, and cut a v0.6.6 as a successor to v0.6.4 so that we can still have a viable mainline for bug fixes and such.

Retract the accidentally-released v0.6.5.

---

.mergify.yml

Per https://blog.mergify.com/strict-mode-deprecation/, the "strict" mode
has been deprecated and will be turned off on 10-Jan-2022. This updates
the config to use the new, approved thing instead of the old thing.

Update mergify configuration.

---

go.mod
go.sum

Change go.mod to use the new fork under cosmos: https://github.com/cosmos/gorocksdb

Update gorocksdb replace directive to use cosmos fork

---

go.mod

Sending out an update to go 1.17 because the go.mod files are clearer and it's easier to audit imports that way. 
Reasoning is here:
https://twitter.com/gadikian/status/1469512833809678342

Update to go 1.17

---

go.mod
go.sum

Without this, tests against boltdb with the race detector on go tip fail
with error messages like:
```
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20200930185726-fdedc70b468f/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
```

Update to latest golang.org/x/sys
